const winasaCatalogs = [
  {id:'200x1200',title:'Porcelana 200x1200',subtitle:'Winasa Porcelain',description:'Formato alongado, ideal para efeito madeira, pavimentos contínuos e projetos contemporâneos com leitura visual mais elegante.',fallback:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=90',pdf:'assets/catalogos/winasa/porcelana-200x1200.pdf'},
  {id:'300x600',title:'Porcelana 300x600',subtitle:'Winasa Porcelain',description:'Formato versátil para parede e pavimento, indicado para soluções residenciais e comerciais.',fallback:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=90',pdf:'assets/catalogos/winasa/porcelana-300x600.pdf'},
  {id:'600x600',title:'Porcelana 600x600',subtitle:'Winasa Porcelain',description:'Formato quadrado de uso amplo, com equilíbrio entre praticidade, estética e aplicação em vários tipos de projeto.',fallback:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=90',pdf:'assets/catalogos/winasa/porcelana-600x600.pdf'},
  {id:'600x1200',title:'Porcelana 600x1200',subtitle:'Winasa Porcelain',description:'Formato grande, visual premium e indicado para espaços amplos, revestimentos sofisticados e projetos comerciais.',fallback:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=90',pdf:'assets/catalogos/winasa/porcelana-600x1200.pdf'},
  {id:'800x800',title:'Porcelana 800x800',subtitle:'Winasa Porcelain',description:'Formato quadrado grande, ideal para ambientes amplos com menos juntas e leitura mais limpa.',fallback:'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200&q=90',pdf:'assets/catalogos/winasa/porcelana-800x800.pdf'}
];

function goHome(){document.getElementById('pg-home').classList.add('act');document.getElementById('pg-factory').classList.remove('act');window.scrollTo({top:0,behavior:'smooth'});}
function scrollToId(id){document.getElementById('pg-home').classList.add('act');document.getElementById('pg-factory').classList.remove('act');setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),50);}
function openFactory(id){if(id!=='winasa')return;document.getElementById('pg-home').classList.remove('act');document.getElementById('pg-factory').classList.add('act');window.scrollTo({top:0,behavior:'smooth'});renderWinasa();}
function renderWinasa(){const grid=document.getElementById('winasaGrid');if(!grid||grid.dataset.ready)return;grid.innerHTML=winasaCatalogs.map(item=>`<div class="catalog-card" onclick="showCatalog('${item.id}')"><div class="img" style="background-image:url('${item.fallback}')"></div><div class="shade"></div><div class="info"><div class="card-type">${item.subtitle}</div><div class="card-title">${item.title.replace(' ','<br>')}</div><div class="card-action">Ver catálogo →</div></div></div>`).join('');grid.dataset.ready='1';showCatalog('200x1200',false);}
function showCatalog(id,scroll=true){const item=winasaCatalogs.find(x=>x.id===id)||winasaCatalogs[0];const panel=document.getElementById('catalogPanel');panel.innerHTML=`<div class="panel-img" style="background-image:url('${item.fallback}')"></div><div class="panel-info"><p class="eyebrow">${item.subtitle}</p><h3>${item.title}</h3><p>${item.description}</p><div class="panel-actions"><button class="btn-line" onclick="openPDF('${item.pdf}')">Abrir catálogo</button><button class="btn-line" onclick="window.open('${item.pdf}','_blank')">Download PDF</button></div></div>`;if(scroll)panel.scrollIntoView({behavior:'smooth',block:'center'});}
function openPDF(src){document.getElementById('pdfViewer').src=src;document.getElementById('pdfModal').classList.add('act');}
function closePDF(){document.getElementById('pdfViewer').src='';document.getElementById('pdfModal').classList.remove('act');}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closePDF();});
